version: '3.8'

services:
  messageservice:
    build:
      context: .
      dockerfile: /Services/Message/MessageService/Dockerfile
    image: messenger-message

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=messengerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
