<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.6.0" />
    <PackageReference Include="Respawn" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Messenger.Identity.Api\Messenger.Identity.Api.csproj" />
  </ItemGroup>

</Project>
