<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Messenger.Message.API</RootNamespace>
    <AssemblyName>Messenger.Message.API</AssemblyName>
    <UserSecretsId>c4050bf2-9493-46d0-af5f-c3c2f562e1e0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Messenger.Message.Application\Messenger.Message.Application.csproj" />
    <ProjectReference Include="..\Messenger.Message.Infrastructure\Messenger.Message.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
